# Generated by Django 4.2 on 2025-10-04 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bitacora_inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.CharField(max_length=80)),
                ('fecha', models.DateField()),
                ('observaciones', models.CharField(max_length=500)),
                ('tipo_ingreso', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='responsable_alamacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_responsable', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipoElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tipoUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.CharField(blank=True, max_length=500)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.tipoelemento')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.tipounidad')),
            ],
        ),
        migrations.CreateModel(
            name='elementos_x_bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.inventario')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.bitacora_inventario')),
                ('tipo_unidad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.tipounidad')),
            ],
        ),
        migrations.CreateModel(
            name='cantidad_x_restauracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('necesario', models.IntegerField()),
                ('restauraciones', models.IntegerField()),
                ('disponible', models.BooleanField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.inventario')),
            ],
        ),
    ]
