# Generated by Django 4.2 on 2025-08-18 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipoElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tipoUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('marca', models.CharField(max_length=50)),
                ('observaciones', models.CharField(max_length=500)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.tipoelemento')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.tipounidad')),
            ],
        ),
    ]
