# Generated by Django 4.2 on 2025-10-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementos_x_bitacora',
            name='tipo_unidad',
        ),
    ]
