# Generated by Django 4.2 on 2025-08-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='marca',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='observaciones',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
