# Generated by Django 4.2 on 2025-08-25 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_inventario_marca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cantidad_x_restauracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('necesario', models.IntegerField()),
                ('restauraciones', models.IntegerField()),
                ('disponible', models.BooleanField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.inventario')),
            ],
        ),
    ]
