# Generated by Django 4.2 on 2025-10-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_elementos_x_bitacora_tipo_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable_alamacen',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
